---
title: "Week 9 assignment data 607"
author: "Keith DeNivo"
date: "2024-03-24"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
https://rpubs.com/divide_by_zero/1166562
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<header>Introduction:</header>
Using New York Times API a JSON file of science articles were scraped.  Selected information can be stored into a data frame in r.
```{r html and libraries}
library(htmlTable)
library(magrittr)
library(jsonlite)
library(tableHTML)
library(rjson)
library(XML)
library(xml2)
library(tidyverse)
library(RCurl)
library(RJSONIO)
library(knitr)
library(httr)



```
<header>Libraries</header>
httr and jsonlite are the key libraries.


```{r json api}
apiurl2 <- GET("https://api.nytimes.com/svc/topstories/v2/science.json?api-key=XZGLFNQG2GlkOtKByTaiAQMgjON1PXGT")
#read in the api data for science articles


apiurl2$status_code

#status should be 200 for successful connection

api_char <- rawToChar(apiurl2$content)

#convert the raw file to something that can be read for fromJSON extract only the content which contains the articles and their information

api_JSON <- fromJSON(api_char, flatten = TRUE)
class(api_JSON)
#fromJSON interprets the JSON code and converts it into a list.

jsonresult <- api_JSON$results
#"results" contains the articles in the list api_JSON

class(jsonresult)
#currently a list
length(jsonresult)

glimpse(jsonresult)

science_articles <- data.frame(c(1:length(jsonresult)))
#initialize a data frame called science articles to store the science article information

for(x in 1:length(jsonresult)){
science_articles[x,2] <- jsonresult[[x]]$title
science_articles[x,3] <- jsonresult[[x]]$url
science_articles[x,4] <- jsonresult[[x]]$published_date
}
#can extract title abstract etc. from the list and store it into a dataframe using a for loop. not optimal but it does transform parts of the list to a dataframe.

glimpse(science_articles)
class(science_articles)
science_articles

``` 

<header>Conclusion/dataframes:</header>
Science articles from NYT API was extracted and the JSON file was converted to a list.  From the list a data frame was constructed.

